version: '3.8'
services:
  db:
    image: postgres:17.4
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: communicationDb
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
